title: Bus Admittance Matrix
description: This project implements the creation of bus admittance matrix in Java, Python and MATLAB

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-scholar

relative_links:
  enabled: true
  collections: true
include:
 - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

remote_theme: pages-themes/dinky

mermaid:
  version: 11.4.1

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

mathjax:
  enable: true
  use_preview: true

scholar:
  style: ieee
  locale: en-US
  source: _bibliography/papers.bib
  sort_by: year
  order: descending