name: Generate and Commit MATLAB Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MATLAB
      run: |
        sudo apt-get update
        sudo apt-get install -y octave

    - name: Add m2html to Octave path
      run: |
        octave --eval "addpath('./makehtmldoc/'); savepath;"

    - name: Verify m2html installation
      run: |
        octave --eval "which m2html"

    - name: Generate Documentation
      run: |
        cd ./Ybus/matlab
        octave --eval "m2html('mfiles', './', 'htmldir', './html/');"

    - name: Commit and Push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m 'Generate and commit MATLAB documentation'
        git push
